// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// find_interval
int find_interval(double x, NumericVector breaks);
RcppExport SEXP _tax4sa_find_interval(SEXP xSEXP, SEXP breaksSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type breaks(breaksSEXP);
    rcpp_result_gen = Rcpp::wrap(find_interval(x, breaks));
    return rcpp_result_gen;
END_RCPP
}
// pit
NumericVector pit(NumericVector income, NumericVector age, NumericVector mtc, NumericVector taxyear);
RcppExport SEXP _tax4sa_pit(SEXP incomeSEXP, SEXP ageSEXP, SEXP mtcSEXP, SEXP taxyearSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type income(incomeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type age(ageSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mtc(mtcSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type taxyear(taxyearSEXP);
    rcpp_result_gen = Rcpp::wrap(pit(income, age, mtc, taxyear));
    return rcpp_result_gen;
END_RCPP
}
// pit_function
double pit_function(double income, double age, double mtc, NumericMatrix brackets, NumericMatrix rebates);
RcppExport SEXP _tax4sa_pit_function(SEXP incomeSEXP, SEXP ageSEXP, SEXP mtcSEXP, SEXP bracketsSEXP, SEXP rebatesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type income(incomeSEXP);
    Rcpp::traits::input_parameter< double >::type age(ageSEXP);
    Rcpp::traits::input_parameter< double >::type mtc(mtcSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type brackets(bracketsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type rebates(rebatesSEXP);
    rcpp_result_gen = Rcpp::wrap(pit_function(income, age, mtc, brackets, rebates));
    return rcpp_result_gen;
END_RCPP
}
// pit_manual
NumericVector pit_manual(NumericVector income, NumericVector age, NumericVector mtc, NumericMatrix brackets, NumericMatrix rebates);
RcppExport SEXP _tax4sa_pit_manual(SEXP incomeSEXP, SEXP ageSEXP, SEXP mtcSEXP, SEXP bracketsSEXP, SEXP rebatesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type income(incomeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type age(ageSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mtc(mtcSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type brackets(bracketsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type rebates(rebatesSEXP);
    rcpp_result_gen = Rcpp::wrap(pit_manual(income, age, mtc, brackets, rebates));
    return rcpp_result_gen;
END_RCPP
}
// tax_calculation
NumericVector tax_calculation(NumericVector income, NumericMatrix brackets);
RcppExport SEXP _tax4sa_tax_calculation(SEXP incomeSEXP, SEXP bracketsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type income(incomeSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type brackets(bracketsSEXP);
    rcpp_result_gen = Rcpp::wrap(tax_calculation(income, brackets));
    return rcpp_result_gen;
END_RCPP
}
// tax_function
double tax_function(double income, NumericMatrix brackets);
RcppExport SEXP _tax4sa_tax_function(SEXP incomeSEXP, SEXP bracketsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type income(incomeSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type brackets(bracketsSEXP);
    rcpp_result_gen = Rcpp::wrap(tax_function(income, brackets));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_tax4sa_find_interval", (DL_FUNC) &_tax4sa_find_interval, 2},
    {"_tax4sa_pit", (DL_FUNC) &_tax4sa_pit, 4},
    {"_tax4sa_pit_function", (DL_FUNC) &_tax4sa_pit_function, 5},
    {"_tax4sa_pit_manual", (DL_FUNC) &_tax4sa_pit_manual, 5},
    {"_tax4sa_tax_calculation", (DL_FUNC) &_tax4sa_tax_calculation, 2},
    {"_tax4sa_tax_function", (DL_FUNC) &_tax4sa_tax_function, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_tax4sa(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
