
#' @title
#' Loading data
#' @description
#' Loading data
#' @details
#' Convenience function to get data into environment
#' @export

load_tax4sa_data <- function() {

  data("NT_Budget_forecasts")
  data("NT_Budget_revenue")
  data("NT_Budget_PIT_rebates")
  data("NT_Budget_PIT_brackets")
  data("NT_S32_revenue")
  data("NT_S32_Table1_revenue")
  data("NT_S32_Table2_expenditure")
  data("NT_S32_Summary")
  data("SARB_Quarterly_Bulletin")
  data("SARB_Quarterly_Bulletin_info")
  data("DMRE_fuel")
  data("STATSSA_P0141_CPI_urban")
  data("STATSSA_P0141_CPI_province")
  data("STATSSA_P0141_CPI_digit")
  data("STATSSA_P0141_CPI_COICOP")
  data("STATSSA_P6410_tourists")
  data("STATSSA_P5041.1_building")
  data("STATSSA_P0151.1_construction")
  data("STATSSA_P4141_electricity")
  data("STATSSA_P0142.7_trade")
  data("STATSSA_P6420_food")
  data("STATSSA_P0043.1_liquidations")
  data("STATSSA_P0043_insolvencies")
  data("STATSSA_P0142.1_PPI")
  data("STATSSA_P2041_mining")
  data("STATSSA_P3041.2_manufacturing")
  data("STATSSA_P6141.2_wholesale")
  data("STATSSA_P6242.1_retail")
  data("STATSSA_P6343.2_vehicles")
  data("STATSSA_P7162_transport")
  data("STATSSA_P0441_GDP")

  data("SARB_monthly_Banks_and_mutual_banks")
  data("SARB_monthly_Capital_market")
  data("SARB_monthly_Counterparts_of_M3")
  data("SARB_monthly_Credit_aggregates")
  data("SARB_monthly_Credit_detail")
  data("SARB_monthly_Deposit_detail")
  data("SARB_monthly_Economic_indicators")
  data("SARB_monthly_International_economic_data")
  data("SARB_monthly_Money_and_banking")
  data("SARB_monthly_National_government_finance")
  data("SARB_monthly_Securitisation")

  invisible(force(NT_Budget_forecasts))
  invisible(force(NT_Budget_revenue))
  invisible(force(NT_Budget_PIT_rebates))
  invisible(force(NT_Budget_PIT_brackets))
  invisible(force(NT_S32_revenue))
  invisible(force(NT_S32_Table1_revenue))
  invisible(force(NT_S32_Table2_expenditure))
  invisible(force(NT_S32_Summary))
  invisible(force(SARB_Quarterly_Bulletin))
  invisible(force(SARB_Quarterly_Bulletin_info))
  invisible(force(DMRE_fuel))
  invisible(force(STATSSA_P0141_CPI_urban))
  invisible(force(STATSSA_P0141_CPI_province))
  invisible(force(STATSSA_P0141_CPI_digit))
  invisible(force(STATSSA_P0141_CPI_COICOP))
  invisible(force(STATSSA_P6410_tourists))
  invisible(force(STATSSA_P5041.1_building))
  invisible(force(STATSSA_P0151.1_construction))
  invisible(force(STATSSA_P4141_electricity))
  invisible(force(STATSSA_P0142.7_trade))
  invisible(force(STATSSA_P6420_food))
  invisible(force(STATSSA_P0043.1_liquidations))
  invisible(force(STATSSA_P0043_insolvencies))
  invisible(force(STATSSA_P0142.1_PPI))
  invisible(force(STATSSA_P2041_mining))
  invisible(force(STATSSA_P3041.2_manufacturing))
  invisible(force(STATSSA_P6141.2_wholesale))
  invisible(force(STATSSA_P6242.1_retail))
  invisible(force(STATSSA_P6343.2_vehicles))
  invisible(force(STATSSA_P7162_transport))
  invisible(force(STATSSA_P0441_GDP))

  invisible(force(SARB_monthly_Banks_and_mutual_banks))
  invisible(force(SARB_monthly_Capital_market))
  invisible(force(SARB_monthly_Counterparts_of_M3))
  invisible(force(SARB_monthly_Credit_aggregates))
  invisible(force(SARB_monthly_Credit_detail))
  invisible(force(SARB_monthly_Deposit_detail))
  invisible(force(SARB_monthly_Economic_indicators))
  invisible(force(SARB_monthly_International_economic_data))
  invisible(force(SARB_monthly_Money_and_banking))
  invisible(force(SARB_monthly_National_government_finance))
  invisible(force(SARB_monthly_Securitisation))


}
