# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Find the interval of a number in a sequence
#'
#' @param x A numeric value.
#' @param breaks A vector of numbers
find_interval <- function(x, breaks) {
    .Call('_tax4sa_find_interval', PACKAGE = 'tax4sa', x, breaks)
}

#' @title
#' Calculate personal income tax liability in South Africa
#' @description
#' Function to calculate personal income tax liability
#' @param income a numeric vector of incomes
#' @param age a numeric vector of ages, which is the age of each individual at the end of the tax year
#' @param mtc a numeric vector of medical tax credits available in the tax year
#' @param taxyear a numeric vector of the tax year for each record, where the number represents the year in which
#'  the tax year ends. For example, 2021 refers to the 2020/21 tax year.
#' @details
#' \code{pit} takes inputs of income (in Rands), age, medical tax credit and the tax year to
#' calculate the tax liability in South Africa.
#' Available for tax years 2010/11 to 2020/21.
#' @export
#' @useDynLib tax4sa
#' @examples
#' # Calculate personal income tax
#' pit(income = 1000000, age = 53, mtc = 2550, taxyear = 2021)
#'
#' # Same calculation in a relatively large dataframe with differing variables
#' individuals <- 1e6
#' df <- data.frame(Taxable_income = round(runif(individuals, 0, 3000000),0),
#'                  Age = round(runif(individuals, 18, 80),0),
#'                  MTC = round(runif(individuals, 0, 6000), 0),
#'                  Tax_year = round(runif(individuals, 2014, 2020), 0))
#'
#' df$Simulated_tax <- pit(df$Taxable_income, df$Age, df$MTC, df$Tax_year)
#'
#' # Or tidyverse way
#' library(dplyr)
#' df <- df %>%
#'   mutate(Simulated_tax = pit(Taxable_income, Age, MTC, Tax_year))
#'
#' # Check pit_manual function for simulations with custom tax tables
#'
#' @export
pit <- function(income, age, mtc, taxyear) {
    .Call('_tax4sa_pit', PACKAGE = 'tax4sa', income, age, mtc, taxyear)
}

#' @title
#' Calculate personal income tax liability based on a tax table, rebate table and medical tax credits
#' @description
#' Function to calculate tax liability using custom tax tables
#' @param income taxable income for the tax year
#' @param age age of each individual at the end of the tax year
#' @param mtc medical tax credits available in the tax year
#' @param table a matrix representing any tax table, specifically the marginal tax rates and brackets
#' @param rebate a matrix representing the rebates available for each age group
#' @details
#' \code{pit_manual} takes a vector of income and age and a matrix representation of the income tax brackets and
#' the rebate available per age to calculate the tax liability.
#' Allowing for custom tax tables make it easier to model policy changes.
#' Since it is implemented in C++ it should be relatively quick and well-suited to large datasets.
pit_function <- function(income, age, mtc, brackets, rebates) {
    .Call('_tax4sa_pit_function', PACKAGE = 'tax4sa', income, age, mtc, brackets, rebates)
}

#' @title
#' Calculate personal income tax liability based on a tax table, rebate table and medical tax credits
#' @description
#' Function to calculate tax liability using custom tax tables
#' @param income taxable income for the tax year
#' @param age age of each individual at the end of the tax year
#' @param mtc medical tax credits available in the tax year
#' @param table a matrix representing any tax table, specifically the marginal tax rates and brackets
#' @param rebate a matrix representing the rebates available for each age group
#' @details
#' \code{pit_manual} takes a vector of income and age and a matrix representation of the income tax brackets and
#' the rebate available per age to calculate the tax liability.
#' Allowing for custom tax tables make it easier to model policy changes.
#' Since it is implemented in C++ it should be relatively quick and well-suited to large datasets.
#' @export
#' @examples
#' # Calculate personal income tax using custom tax tables
#' pit_manual(income = 1000000, age = 53, mtc = 2550,
#'            brackets = Tax_tables$PIT_brackets_2021, rebates = Tax_tables$PIT_rebates_2021)
pit_manual <- function(income, age, mtc, brackets, rebates) {
    .Call('_tax4sa_pit_manual', PACKAGE = 'tax4sa', income, age, mtc, brackets, rebates)
}

#' @title
#' Calculate tax liability based on a tax table
#' @description
#' Function to calculate tax liability using custom tax tables
#' @param income any amount to apply to a tax table
#' @param table a matrix representing any tax table
#' @details
#' \code{pit_manual} takes a vector of income and age and a matrix representation of the income tax brackets and
#' the rebate available per age to calculate the tax liability.
#' Allowing for custom tax tables make it easier to model policy changes.
#' Since it is implemented in C++ it should be relatively quick and well-suited to large datasets.
#' @export
tax_calculation <- function(income, brackets) {
    .Call('_tax4sa_tax_calculation', PACKAGE = 'tax4sa', income, brackets)
}

#' @title
#' Calculate tax liability based on a tax table
#' @description
#' Function to calculate tax liability using custom tax tables
#' @param income any amount to apply to a tax table
#' @param table a matrix representing any tax table
#' @details
#' \code{pit_manual} takes a vector of income and age and a matrix representation of the income tax brackets and
#' the rebate available per age to calculate the tax liability.
#' Allowing for custom tax tables make it easier to model policy changes.
#' Since it is implemented in C++ it should be relatively quick and well-suited to large datasets.
tax_function <- function(income, brackets) {
    .Call('_tax4sa_tax_function', PACKAGE = 'tax4sa', income, brackets)
}

